version: '3.2'

networks:
  pichain:
    external:
      name: pichain
      
services:
  ca_org2_example_com:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ip-172-31-20-5
    image: hyperledger/fabric-ca:amd64-1.4.0
    hostname: ca.org2.example.com
    environment:
      - DOCKER_HOST=ca.org2.example.com:8054
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org2.example.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/667bfaa3db61c33f4e21774693981c4d22064ab6a032911f155369e5b028f10d_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/667bfaa3db61c33f4e21774693981c4d22064ab6a032911f155369e5b028f10d_sk
    ports:
      - 8054:8054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d -p 8054'
    volumes:
      - ../../crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      pichain:
        aliases:
          - ca.org2.example.com
  couchdb1:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == basic-hostname
    hostname: couchdb1
    image: hyperledger/fabric-couchdb:amd64-0.4.14
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "6984:5984"
    logging:
      options:
        max-size: 100m
    networks:
      - pichain


  